ale_desc = '''
Estas cervezas son las también llamadas cervezas de alta fermentación debido a que su levadura fermenta en la parte de arriba del recipiente (aunque los equipos modernos permiten depositarla al fondo) y además lo hace a mayor temperatura (15-25ºC) que las Lagers y, por tanto, en menos tiempo. Una Ale puede estar lista en 2 o 3 semanas debido a la acción rápida de la levadura, mientras que una Lager puede tardar hasta 2 o 3 meses. Esta levadura termina depositándose en el fondo del mosto en los últimos días de fermentación, aguantando una mayor variación de temperatura y alcohol. Su alta fermentación hace que se suela usar agua dura, o sea, rica en sales minerales.

Se trata por lo general de cervezas con sabores más complejos que las Lagers, en las que incluso la levadura aporta a menudo cierto toque afrutado, pues la mayor temperatura permite liberar ésteres adicionales. Su consumo suele ser a una temperatura superior (7-12ºC) que las Lagers para poder apreciar mejor la complejidad de sabor, permitiendo a menudo un mayor papel del lúpulo. Hay muchas variedades de Ales debido a la facilidad para modificarla añadiendo ingredientes o variando los tiempos en cada proceso.

Las Ales son mucho más antiguas que las Lagers, remontándose a los orígenes prehistóricos de elaboración de cerveza, precedidas únicamente por los brebajes fermentados espontáneamente.

En la Inglaterra del siglo XIV, el término Ale era usado (y según algunos debería seguir siendo todavía) para referirse a la única bebida de cereal malteado consumida en Inglaterra, la cual no usaba lúpulo. El término siguió usándose allí desde el XV para diferenciar esta bebida de las cervezas con lúpulo que empezaban a llegar desde el continente, traídas por inmigrantes alemanes y holandeses, a las cuales se les reservaba el nombre de beer. Las Ales no tardaron en incorporar lúpulo, pero siempre en menor cantidad que las beers. Huelga decir que esta distinción se ha diluido con el tiempo, como demuestra la existencia de Ales fuertemente lupuladas como las IPAs. En cuanto al origen del término, deriva del inglés antiguo Alu o Ealu y a su vez del Öl nórdico. Remontándonos aún más atrás, ha sido relacionado con la raíz indoeuropea “alu- (-d, -t)” (“amargo”) o con el griego Aluein (“Estar turbado, alucinar”), quizás en referencia a sus usos religiosos para inducir visiones
'''
